### PR TITLE
src/BnToOsslMath.h: fix build with openssl 3.3.x

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure with openssl 3.3.x:

```
In file included from BnValues.h:327,
                 from Global.h:80,
                 from Tpm.h:78,
                 from AuditCommands.c:62:
TpmToOsslMath.h:83:5: error: #error Untested OpenSSL version
   83 | #   error Untested OpenSSL version
      |     ^~~~~
```

Fixes:
 - http://autobuild.buildroot.org/results/2fb5e1cb792fe25ef860ff8111622cd1ff3770bf

### CODE REVIEW

**Comment by kgoldman** [comment]
Thanks, fixed and closed.
